version: '3.9'

services:
  web:
    build: .
    container_name: skn9_llm
    volumes:
      - .:/code
      - ./static:/code/static
    env_file:
      - .env
    expose:
      - "8000"
    command: gunicorn llm.wsgi:application --bind 0.0.0.0:8000 --config gunicorn.conf.py

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
    depends_on:
      - web
